services:
    db:
        image: mysql:8.0
        container_name: laravel-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin","ping","-h","localhost"]
            interval: 5s
            timeout: 2s
            retries: 5
        networks:
            - laravel

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        env_file:
            - .env
        volumes:
            - .:/var/www
        depends_on:
            db:
                condition: service_healthy
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: laravel-web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
